language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"
  - VERSION="8.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo apt-get install python-matplotlib
  - sudo pip install gitlab3
  - git clone --depth=1 https://github.com/odoo/odoo-extra ~/odoo-extra

script:
  - travis_run_tests

after_success:
  coveralls
